# Copyright (C) 2022 Magenta ApS, http://magenta.dk.
# Contact: info@magenta.dk.
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


stages:
  - build

variables:
  UBUNTU_RELEASE: "22.04"
  SOURCE_ISO: "ubuntu-22.04.4-live-server-amd64.iso"
  # NOTE: The purpose of this is to have something to uniquely identify the output ISO name by under "artifacts", as it has no access to the DESTINATION_ISO variable
  DESTINATION_ISO_PREFIX: "os2bpc-kiosk"
  ARCHITECTURE: "x64"

# Build stage
#############

Build ISO image:
  stage: build
  needs: []
  when: manual
  image: ubuntu:${UBUNTU_RELEASE}
  before_script:
    - apt-get -y update > /dev/null
    - apt-get -y install fdisk wget sudo apt-utils figlet > /dev/null
    - cd image
    - wget --progress=bar:force --continue http://releases.ubuntu.com/${UBUNTU_RELEASE}/${SOURCE_ISO}
  script:
    - VERSION=$(cat ../VERSION)
    # NOTE: DESTINATION_ISO is both used as the ISO name AND the path to the outputted ISO - it must be valid for both
    # NOTE: Max length of the file name is 32 characters incl. the extension, otherwise xorriso complains
    - DESTINATION_ISO=${DESTINATION_ISO_PREFIX}-${VERSION}-${UBUNTU_RELEASE}-${ARCHITECTURE}
    - ./build_os2borgerpc_kiosk_image.sh ./${SOURCE_ISO} ${DESTINATION_ISO}
  cache:
    paths:
      - image/${SOURCE_ISO}
  artifacts:
    paths:
      - image/${DESTINATION_ISO_PREFIX}*.iso
    expire_in: 1 week
