# Copyright (C) 2022 Magenta ApS, http://magenta.dk.
# Contact: info@magenta.dk.
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


stages:
  - build

variables:
  UBUNTU_RELEASE: "22.04"
  SOURCE_ISO_NAME: "ubuntu-22.04.4-live-server-amd64.iso"

# Build stage
#############

Build ISO image:
  stage: build
  needs: []
  when: manual
  image: ubuntu:${UBUNTU_RELEASE}
  before_script:
    - apt-get -y update > /dev/null
    - apt-get -y install fdisk wget sudo apt-utils figlet > /dev/null
    - cd image
    - wget --progress=bar:force --continue http://releases.ubuntu.com/${UBUNTU_RELEASE}/${SOURCE_ISO_NAME}
  script:
    - VERSION=$(cat ../VERSION)
    # Note: Max length of the file name is 32 characters incl. the extension, otherwise xorriso complains
    - DESTINATION_ISO_PATH=../os2bpc-kiosk-$VERSION-${UBUNTU_RELEASE}-x64
    - ./build_os2borgerpc_kiosk_image.sh ./${SOURCE_ISO_NAME} ${DESTINATION_ISO_PATH}
  cache:
    paths:
      - image/${SOURCE_ISO_NAME}
  artifacts:
    paths:
      - ./*.iso
    expire_in: 1 week
