#!/usr/bin/env bash

if [[ $UID -ne 0 ]]
then
	echo "Denne kommando skal køres som root"
	exit 1
fi

# Setup the OS2BorgerPC client on an Ubuntu Server

DIR=$(dirname ${BASH_SOURCE[0]})

# Avoid script stopping because it wants user input
export DEBIAN_FRONTEND=noninteractive

# Set proper, restricted permissions on superuser homedir
chmod -R 700 /home/superuser

# Install all necessary packages and dependencies
$DIR/install_dependencies.sh

# Prepare to run jobs
mkdir -p /var/lib/os2borgerpc/jobs
chmod -R og-r /var/lib/os2borgerpc

# Prepare to run security events
mkdir -p /etc/os2borgerpc/security/

# Set product in configuration
PRODUCT="os2borgerpc kiosk"
set_os2borgerpc_config os2_product "$PRODUCT"

# Set version in configuration
VERSION=$(cat "$DIR"/VERSION)
set_os2borgerpc_config os2borgerpc_version "$VERSION"

# Setup Chromium user
USER="chrome"
if ! id $USER &>/dev/null; then
  useradd $USER -m -p 12345 -s /bin/bash -U
fi

# Setup autologin of default user
mkdir --parents /etc/systemd/system/getty@tty1.service.d /usr/share/os2borgerpc/bin

AUTOLOGIN_SCRIPT="/usr/share/os2borgerpc/bin/autologin.sh"
AUTOLOGIN_COUNTER="/etc/os2borgerpc/login_counter.txt"
COUNTER_RESET_SERVICE="/etc/systemd/system/reset_login_counter.service"
MAXIMUM_CONSECUTIVE_AUTOLOGINS=3

# Note: The empty ExecStart is not insignificant!
# By default the value is appended, so the empty line changes it to an override
# We make agetty use our own login-program instead of /bin/login
# so we can customize the behavior
cat << EOF > /etc/systemd/system/getty@tty1.service.d/override.conf
[Service]
ExecStart=
ExecStart=-/sbin/agetty --noissue --login-program $AUTOLOGIN_SCRIPT --autologin $USER %I $TERM
Type=idle
EOF

# Create the login script
cat << EOF > $AUTOLOGIN_SCRIPT
#! /usr/bin/env bash
COUNTER=\$(cat $AUTOLOGIN_COUNTER)
COUNTER=\$((COUNTER+1))
echo \$COUNTER > $AUTOLOGIN_COUNTER
if [ \$COUNTER -le $MAXIMUM_CONSECUTIVE_AUTOLOGINS ]; then
  if [ \$COUNTER -gt 1 ]; then
    # Sleep before autologin attempts other than the first
    sleep 10
  fi
  # Autologin as $CUSER
  /bin/login -f $CUSER
else
  # Regular login prompt
  /bin/login
fi
EOF

chmod 700 $AUTOLOGIN_SCRIPT

# Create login counter
echo "0" > $AUTOLOGIN_COUNTER

# Create service to reset counter when
# the computer is booted
cat << EOF > $COUNTER_RESET_SERVICE
[Unit]
Description=Reset the autologin counter when the computer starts

[Service]
Type=oneshot
ExecStart=sh -c 'echo "0" > $AUTOLOGIN_COUNTER'

[Install]
WantedBy=multi-user.target
EOF

systemctl enable --now "$(basename $COUNTER_RESET_SERVICE)"

# Create script to rotate screen
cat << EOF > /usr/share/os2borgerpc/bin/rotate_screen.sh
#!/usr/bin/env sh

set -x

TIME=\$1
ORIENTATION=\$2

sleep \$TIME

export XAUTHORITY=/home/$USER/.Xauthority

# --listactivemonitors lists the primary monitor first
ALL_MONITORS=\$(xrandr --listactivemonitors | tail -n +2 | cut --delimiter ' ' --fields 6)

# Make all connected monitors display what the first monitor displays, rather than them extending the desktop
PRIMARY_MONITOR=\$(echo "\$ALL_MONITORS" | head -n 1)
OTHER_MONITORS=\$(echo "\$ALL_MONITORS" | tail -n +2)
echo "\$OTHER_MONITORS" | xargs -I {} xrandr --output {} --same-as "\$PRIMARY_MONITOR"

# Rotate screen - and if more than one monitor, rotate them all.
echo "\$ALL_MONITORS" | xargs -I {} xrandr --output {} --rotate \$ORIENTATION
EOF

chmod +x /usr/share/os2borgerpc/bin/rotate_screen.sh

# Fix dpkg settings
cat << EOF > /etc/apt/apt.conf.d/local
Dpkg::Options {
   "--force-confdef";
   "--force-confold";
};
Dpkg::Lock {Timeout "300";};
EOF

#  Connect to the admin system
register_new_os2borgerpc_client.sh
